### ISSUE TITLE
error when trying to display the number of visit in a partial in backend

### ISSUE THREAD

**Issue by chrisvidal** [dead23angel/octovisit#3]
in my model `fields.yaml` I have:
```
_total_visit:
            label: "Total visit"
            type: partial
            path: ~/plugins/author/xcv/models/lesson/_total_visit.htm
```

in the partial `_total_visit.htm` I have
```
<?= $model->visit(); ?>
```

error thrown:
```
Object of class CWTeam\OctoVisit\PendingVisit could not be converted to string
```
